name: Continuous integration
on:
  push:
    tags-ignore: ['*']
    branches:
      - '**'
env:
  AWS_DEFAULT_REGION: "eu-west-1"
  AWS_GH_ACTION_ROLE: ${{ vars.TOOL_GH_ACTION_ROLE_ARN }}
  CICD_ARTIFACTORY_KEY: ${{ secrets.CICD_ARTIFACTORY_KEY }}
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # read is required for actions/checkout
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  #        TODO replace by your language
  #      - uses: pbstck/actions/setup-go@v1
  #        with:
  #          go-version: '1.14.2'
  check_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pbstck/actions/setup-terraform@v1
      - uses: pbstck/actions/setup-cloud@v1
      - run: make validate_infra
  test:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      #        TODO replace by your language
      #      - uses: pbstck/actions/setup-go@v1
      #        with:
      #          go-version: '1.14.2'
      - run: make test
  lint:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      #        TODO replace by your language
      #      - uses: pbstck/actions/setup-go@v1
      #        with:
      #          go-version: '1.14.2'
      - uses: pbstck/actions/setup-terraform@v1
      - name: lint project
        run: make lint/check
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
#        TODO replace by your language
#      - uses: pbstck/actions/setup-go@v1
#        with:
#          go-version: '1.14.2'
      - run: make build
      - uses: actions/upload-artifact@v3
        if: ${{ github.event.ref == 'refs/heads/main' }}
        with:
          name: binary
#          path: bin/dynamo-crawler.zip TODO: replace with your path

  deliver:
    if: ${{ github.event.ref == 'refs/heads/main' }}
    needs: [ build, test, lint, check_infra ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: binary
          path: bin/
      - uses: pbstck/actions/setup-cloud@v1
      - name: deliver artifact
        run: make deliver
