name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: pbstck/actions/lint-title@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
