name: Update aws-lib in all RUST projects

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

env:
  GH_TOKEN: ${{ secrets.ORG_SECRET }}

jobs:
  update_project:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ browser-tracing ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./taskfiles
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./${{matrix.project}}
          repository: 'pbstck/${{matrix.project}}'
          token: ${{ env.GH_TOKEN }}
      - name: Copy taskfile
        run: |
          mkdir -p ./${{matrix.project}}/taskfile
          cp ./taskfile/* ./${{matrix.project}}/taskfile/
      - name: "Create PR"
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ env.GH_TOKEN }}
          commit-message: "build(taskfile): bump taskfile to latest version"
          title: "build(taskfile): bump taskfile to latest version"
          body: "bump taskfile to latest version"
          branch: "update-taskfiles"
          base: "main"
          draft: false

